
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://127.0.0.1/SpringCloud_Sell?CharacterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        mymessage:
          group: order
          content-type: application/json
#20181226
PRODUCT:
  ribbon:
    NFloadBalancerRuleClassName:com.netflix.loadbalancer.RandomRule
  redis:
    host: localhost
    port: 6379
env:
  dev1
